---
version: "3.8"
services:
  movies:
    image: azaroddin/dockermovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: azaroddin/dockertrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: azaroddin/dockerdth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: azaroddin/dockerreacharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
